language: python
dist: xenial
python:
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "3.6"
  - "3.6-dev"
  - "3.7"
  - "3.7-dev"
  - "pypy3.5"
env:
  - MAKE_RUN=ci
matrix:
  fast_finish: true
  allow_failures:
  - python: 3.5-dev
  - python: 3.6-dev
  - python: 3.7-dev
  - python: 3.8-dev
  - python: nightly

  include:
    - python: 2.7
      env:
      - MAKE_RUN=ci-py2
    - python: 3.8-dev
      env:
      - MAKE_RUN=tests-py3
    - python: nightly
      env:
      - MAKE_RUN=tests-py3

notifications:
  email:
    recipients:
      - secure: "bdFDE8d50zWO9XWc1gQ4OPDrbvjZXOum1AIchDqwYXr8C7iluJcS2q+z5mczdvHlW3XflcjALl+x81hekdBk+8L6AJuAj5MhTF+HvjFL2EkY7q0V+seLTltYhoqnnlf0BlYGwoILBbDX2p/GYHNUOqWvCtGlJGMpy0qM3R8t5Vw="
install:
  - pip install -U 'setuptools>=32.2.0'
  - pip install .
script: make ${MAKE_RUN}
